### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by htcml** [Featuretools/predict-appointment-noshow#4]
When running this step: 
fm, features = ft.dfs(entityset=es,
                      target_entity='appointments',
                      agg_primitives=['count', 'percent_true'],
                      trans_primitives=['is_weekend', 'weekday', 'day', 'month', 'year'],
                      max_depth=3,
                      approximate='6h',
                      cutoff_time=cutoff_times[20000:],
                      verbose=True)

I got the following error. Please help!

AttributeError: Cutoff time DataFrame must contain a column with either the same name as the target entity time_index or a column named "time"

**Comment by kmax12** [comment]
Thanks for sharing the error. We need to update the repo to work with the latest version of featuretools. Will do it shortly

**Comment by thehomebrewnerd** [comment]
@htcml The error you are seeing is being addressed by pull request #3. Until that fix is merged in, you can run the version of the notebook contained in the `update-reqs` branch, and this should fix your issue.

If you encounter additional problems, please let us know!

**Comment by thehomebrewnerd** [comment]
Closed by #3
